# Generated by Django 4.1.7 on 2023-03-04 06:35

import BankApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('zip_code', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('DOJ', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('s_number', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('s_type', models.CharField(max_length=80)),
                ('is_freezed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('SSN', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to=BankApp.models.upload_path)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('address_zip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.address')),
                ('c_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(auto_now_add=True)),
                ('receiver_SSN', models.IntegerField()),
                ('sender_SSN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('l_number', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration', models.CharField(max_length=40)),
                ('status', models.SmallIntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.admin')),
                ('user_SSN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_number', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_obtained', models.DateField(auto_now_add=True)),
                ('user_SSN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.user')),
            ],
        ),
    ]
