# Generated by Django 4.1.7 on 2023-03-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('a_number', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('s_number_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.service')),
                ('user_SSN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankApp.user')),
            ],
        ),
    ]
