# Generated by Django 4.1.7 on 2023-03-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BankApp.admin'),
        ),
    ]
