# Generated by Django 4.1.7 on 2023-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0004_alter_loan_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_type',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
