# Generated by Django 4.1.7 on 2023-03-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0005_alter_service_s_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_zip_code',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='c_code',
            new_name='nationality',
        ),
    ]
